M48
; DRILL file {KiCad 9.0.4} date 2025-09-13T13:51:10-0400
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-09-13T13:51:10-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.4
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.300
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C1.100
%
G90
G05
T1
X136.0Y-47.5
T2
X135.738Y-53.5
X138.278Y-53.5
M30
